
-- Add new columns to store more project details
ALTER TABLE public.projects
ADD COLUMN long_description TEXT,
ADD COLUMN client TEXT,
ADD COLUMN budget TEXT,
ADD COLUMN area TEXT,
ADD COLUMN team_members JSONB,
ADD COLUMN challenges JSONB,
ADD COLUMN solutions JSONB,
ADD COLUMN results JSONB,
ADD COLUMN testimonial JSONB;

-- Clear existing projects to avoid duplicates when seeding
TRUNCATE TABLE public.projects RESTART IDENTITY CASCADE;

-- Seed projects data from the application's mock data
INSERT INTO public.projects (id, name, slug, category, location, status, year, description, long_description, client, budget, area, hero_image_url, gallery_images, tags, specifications, timeline, team_members, challenges, solutions, results, testimonial) VALUES
(
  1,
  'Metro City Fuel Complex',
  'metro-city-fuel-complex',
  'construction',
  'Houston, TX',
  'Completed',
  2024,
  'Complete fuel station construction with 12 dispensers and modern convenience store.',
  'A comprehensive fuel complex project featuring state-of-the-art dispensing technology, environmental safety systems, and a modern convenience store. This project showcases our expertise in large-scale fuel infrastructure development with a focus on efficiency and environmental compliance.',
  'Metro Energy Corp',
  '$2.5M',
  '3.2 acres',
  'https://images.unsplash.com/photo-1545558014-8692077e9b5c?w=800&h=600&fit=crop',
  '[{"url":"https://images.unsplash.com/photo-1578662996442-48f60103fc96?w=600&h=400&fit=crop","alt":"Modern convenience store interior","type":"gallery"},{"url":"https://images.unsplash.com/photo-1581092795360-fd1ca04f0952?w=600&h=400&fit=crop","alt":"Underground storage tank installation","type":"technical"}]'::jsonb,
  '["Construction", "POS Systems", "Environmental Compliance"]'::jsonb,
  '[{"name":"Dispensers","value":"12 Multi-Product Dispensers"},{"name":"Storage Capacity","value":"30,000 gallons"},{"name":"Fuel Types","value":"Regular, Premium, Diesel"},{"name":"Payment Systems","value":"EMV, NFC, Mobile Pay"},{"name":"Monitoring","value":"Real-time leak detection"},{"name":"POS System","value":"Cloud-based management"}]'::jsonb,
  '[{"date":"2024-02-28","description":"Site survey, permits, and detailed engineering","status":"completed"},{"date":"2024-05-15","description":"Site preparation and infrastructure installation","status":"completed"},{"date":"2024-06-01","description":"System testing and final inspection","status":"completed"}]'::jsonb,
  '[{"name":"John Rodriguez","role":"Project Manager"},{"name":"Sarah Chen","role":"Lead Engineer"},{"name":"Mike Thompson","role":"Construction Supervisor"}]'::jsonb,
  '["Complex underground utility network required careful coordination","Environmental compliance in urban setting","Maintaining traffic flow during construction"]'::jsonb,
  '["Advanced 3D mapping and coordination with utility companies","Implementation of enhanced environmental monitoring systems","Phased construction approach to minimize disruption"]'::jsonb,
  '["Project completed 2 weeks ahead of schedule","100% environmental compliance maintained","Customer satisfaction rating: 98%","Zero safety incidents during construction"]'::jsonb,
  '{"quote":"Martka Engineering exceeded our expectations in every aspect of this project. Their attention to detail and commitment to environmental safety was outstanding.","author":"David Martinez","position":"Operations Director","company":"Metro Energy Corp"}'::jsonb
),
(
  2,
  'Highway Express Station',
  'highway-express-station',
  'installation',
  'Dallas, TX',
  'Completed',
  2024,
  'Advanced dispenser installation with EMV payment systems and real-time monitoring.',
  'A high-tech fuel dispensing installation featuring the latest in payment technology and monitoring systems. This project demonstrates our capability to integrate cutting-edge technology with reliable fuel dispensing infrastructure.',
  'Express Fuel Networks',
  '$850K',
  '1.8 acres',
  'https://images.unsplash.com/photo-1578662996442-48f60103fc96?w=800&h=600&fit=crop',
  '[{"url":"https://images.unsplash.com/photo-1545558014-8692077e9b5c?w=600&h=400&fit=crop","alt":"Installation process documentation","type":"gallery"}]'::jsonb,
  '["Installation", "EMV Systems", "Monitoring"]'::jsonb,
  '[{"name":"Units","value":"8 High-Speed Dispensers"},{"name":"Flow Rate","value":"10 GPM per nozzle"},{"name":"Technology","value":"EMV Level 3 Certified"}]'::jsonb,
  '[{"date":"2024-03-15","description":"Dispenser and system installation","status":"completed"}]'::jsonb,
  '[{"name":"Alex Johnson","role":"Installation Lead"},{"name":"Maria Garcia","role":"Technical Specialist"}]'::jsonb,
  '["Integration with existing fuel management systems","EMV compliance requirements"]'::jsonb,
  '["Custom API development for seamless integration","Comprehensive EMV certification process"]'::jsonb,
  '["Successful EMV Level 3 certification","25% increase in transaction processing speed","Zero downtime during installation"]'::jsonb,
  null
),
(
  3,
  'Green Valley Infrastructure',
  'green-valley-infrastructure',
  'infrastructure',
  'Austin, TX',
  'In Progress',
  2024,
  'Custom fuel infrastructure design for environmentally sensitive location.',
  'An innovative infrastructure project focused on environmental sustainability and protection. This project showcases our commitment to eco-friendly fuel infrastructure solutions.',
  'Green Valley Development',
  '$1.8M',
  '2.5 acres',
  'https://images.unsplash.com/photo-1581092795360-fd1ca04f0952?w=800&h=600&fit=crop',
  '[]'::jsonb,
  '["Infrastructure", "Environmental", "Custom Design"]'::jsonb,
  '[{"name":"Containment","value":"Double-wall construction"},{"name":"Monitoring","value":"Continuous leak detection"},{"name":"Compliance","value":"EPA Tier 3 standards"}]'::jsonb,
  '[{"date":"2024-03-31","description":"Environmental impact assessment and design","status":"completed"},{"date":"2024-06-30","description":"Site preparation and foundation work","status":"in_progress"}]'::jsonb,
  '[{"name":"Dr. Emily Watson","role":"Environmental Engineer"},{"name":"Robert Kim","role":"Project Coordinator"}]'::jsonb,
  '["Sensitive environmental location","Strict regulatory requirements"]'::jsonb,
  '["Advanced environmental monitoring systems","Collaborative approach with regulatory agencies"]'::jsonb,
  '["Environmental impact assessment approved","All permits obtained ahead of schedule"]'::jsonb,
  null
);
