// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uxhgktnlvnavtqdevbdt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InV4aGdrdG5sdm5hdnRxZGV2YmR0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5ODM5NjUsImV4cCI6MjA2NTU1OTk2NX0.6dQGRavrU9jojbJ76pKF-Ln33ZqMdhSxuaKlqXkHLsY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);